resolver: lts-9.21
packages:
- '.'
- location:
    git: https://github.com/positiondev/larceny.git
    commit: 48dfe03dafff5eb82da3ea270e89f9bfc7291c86
  extra-dep: true
- location:
    git: https://github.com/dbp/zip-conduit.git
    commit: 098ba00ae02ae3a55a2b918327623e6f6e19d478
  extra-dep: true
extra-deps:
- html-entities-1.1.4.2
- logging-3.0.5
